In [1]:
import pandas as pd
import re
import os

In [10]:
df = pd.DataFrame()



df = pd.read_csv("data/0e01b11087c9475dbab3b1c42354c6a7.abundance.tsv", sep="\t", skiprows=4)

df

,chr1,StringTie,transcript,16462,29338,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; cov ""1.403489""; FPKM ""3.728386""; TPM ""6.058838"";"
0,chr1,StringTie,exon,16462,16765,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; ex..."
1,chr1,StringTie,exon,16858,17055,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; ex..."
2,chr1,StringTie,exon,17233,17368,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; ex..."
3,chr1,StringTie,exon,17606,17742,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; ex..."
4,chr1,StringTie,exon,17915,18061,1000,-,.,"gene_id ""STRG.1""; transcript_id ""STRG.1.1""; ex..."
...,...,...,...,...,...,...,...,...,...
230804,ERCC-00168,StringTie,exon,1,1024,1000,+,.,"gene_id ""STRG.22826""; transcript_id ""STRG.2282..."
230805,ERCC-00170,StringTie,transcript,1,1023,1000,+,.,"gene_id ""STRG.22827""; transcript_id ""STRG.2282..."
230806,ERCC-00170,StringTie,exon,1,1023,1000,+,.,"gene_id ""STRG.22827""; transcript_id ""STRG.2282..."
230807,ERCC-00171,StringTie,transcript,1,505,1000,+,.,"gene_id ""STRG.22828""; transcript_id ""STRG.2282..."
230808,ERCC-00171,StringTie,exon,1,505,1000,+,.,"gene_id ""STRG.22828""; transcript_id ""STRG.2282..."

In [ ]:
directory = r'/data/'

for filename in os.listdir(directory):
    if filename.endswith(".tsv"):
        
        print(os.path.join(directory, filename))
    else:
        continue

In [ ]:
file = open("data/0e01b11087c9475dbab3b1c42354c6a7.abundance.tsv", "r")


def clean(x):
     return x[x.find("gene_id"):]

all_lines = file.readlines()
all_lines = all_lines[4:]

all_lines = [clean(x) for x in all_lines]

print(all_lines[1])

# line = all_lines[0]

# cols = line.split(";")
# key_val =  cols[0].split(" ")

# print(key_val[1].strip('"'))

all_data = []
for line in all_lines:
    
    cols = line.split(";")[:4]

    data = dict()

    for key_val in cols:

        key_val =  key_val.split(" ")
        print(cols, "\n", key_val)
        data[key_val[0]] = key_val[1].strip('"')


    all_data.append(data)


df = pd.DataFrame(all_data).fillna('')
print(df)

In [43]:
directory = "out/"
filename = "aaaeee01_cleaned.csv"


joint = os.path.join(directory, filename)


final_df = pd.DataFrame()

gene_name = filename.split("_")[0]

temp_df = pd.read_csv(joint)
temp_df = temp_df.rename(columns={"TPM":gene_name})
temp_df = temp_df.dropna(subset=["ref_gene_id"])
temp_df = temp_df.set_index("ref_gene_id")
temp_df = temp_df[[gene_name]]

temp_df.reset_index()

# filename = "aaaeee04_cleaned.csv"


# joint = os.path.join(directory, filename)


# gene_name = filename.split("_")[0]

# temp2 =  pd.read_csv(joint)
# temp2 = temp2.rename(columns={"TPM":gene_name})
# temp2 = temp2.dropna(subset=[gene_name, "ref_gene_id"], axis=0, how="any")
# temp2 = temp2.set_index("ref_gene_id")
# temp2 = temp2[[gene_name]]

# temp2


# final_df = pd.concat([temp_df, temp2])
# final_df = final_df.dropna(axis=0, how='all')
# final_df = final_df.fillna(value=0)


# final_df

         ref_gene_id  aaaeee01
0  ENSG00000278267.1  3.336915
1  ENSG00000278267.1       NaN
2  ENSG00000239945.1  0.245468

In [2]:
df = pd.read_csv("input.tsv",
sep="\t", 
skiprows=4, 
header=0, 
names=["seqname", "source", "feature",  "start",   "end",     "score",   "strand",  "frame", "attributes"])

In [3]:
df["feature"]  = df["feature"].astype("category")
df["strand"]  = df["strand"].astype("category")

In [4]:
df.describe(include = "all")
df.groupby("strand").count()

        seqname  source  feature   start     end   score   frame  attributes
strand
+        118075  118075   118075  118075  118075  118075  118075      118075
-        112626  112626   112626  112626  112626  112626  112626      112626
.           108     108      108     108     108     108     108         108

In [69]:
df.tail()

,seqname,source,feature,start,end,score,strand,frame,attributes
230804,ERCC-00168,StringTie,exon,1,1024,1000,+,.,"gene_id ""STRG.22826""; transcript_id ""STRG.2282..."
230805,ERCC-00170,StringTie,transcript,1,1023,1000,+,.,"gene_id ""STRG.22827""; transcript_id ""STRG.2282..."
230806,ERCC-00170,StringTie,exon,1,1023,1000,+,.,"gene_id ""STRG.22827""; transcript_id ""STRG.2282..."
230807,ERCC-00171,StringTie,transcript,1,505,1000,+,.,"gene_id ""STRG.22828""; transcript_id ""STRG.2282..."
230808,ERCC-00171,StringTie,exon,1,505,1000,+,.,"gene_id ""STRG.22828""; transcript_id ""STRG.2282..."

In [70]:
new_df = df.loc[df["feature"] == "transcript"]

In [71]:
def convert_to_list(x):
    #outdf = pd.DataFrame(columns= ["gene_id", "transcript_id","exon_number", "reference_id","ref_gene_id","cov", "FPKM", "TPM" ])
    
    tmp_dict = dict()

    split_key_val_pairs = x.split(";")

    split_key_val_pairs = [x.strip(" ") for x in split_key_val_pairs]

    for key_val_pair in split_key_val_pairs:

        key_val_arr = key_val_pair.split(" ")
        if(len(key_val_arr) >1):
            clean_key = key_val_arr[0].strip()
            clean_val = key_val_arr[1].strip('"').strip()
            tmp_dict[clean_key] = clean_val

    #outdf.append(tmp_dict, ignore_index=True)
    return pd.Series(tmp_dict)

In [72]:
wf = pd.concat([new_df.drop(["attributes", "seqname", "source", "start", "end", "strand", "frame", "yeet"], axis=1),
new_df["attributes"].apply(convert_to_list)], axis=1)

In [85]:
wf = wf[["TPM", "transcript_id"]]
wf.groupby("transcript_id")

In [28]:
ddf = new_df[["feature", "strand","seqname"]].join(new_df["yeet"].str.split(" ", expand=True))
ddf

,feature,strand,seqname,0,1,2,3,4,5,6,7,8
7,transcript,-,chr1,STRG.2,STRG.2.1,ENST00000619216.1,ENSG00000278267.1,MIR6859-1,0.772974,2.053415,3.336915,
9,transcript,-,chr1,STRG.3,STRG.3.1,ENST00000495576.1,ENSG00000239945.1,RP11-34P13.8,0.056861,0.151052,0.245468,
12,transcript,-,chr1,STRG.4,STRG.4.1,ENST00000595919.1,ENSG00000269981.1,RP11-34P13.16,0.052113,0.138439,0.224971,
14,transcript,-,chr1,STRG.5,STRG.5.1,ENST00000493797.1,ENSG00000239906.1,RP11-34P13.14,0.082559,0.219319,0.356406,
17,transcript,-,chr1,STRG.6,STRG.6.1,2.926664,7.774721,12.634358,,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
230801,transcript,+,ERCC-00165,STRG.22825,STRG.22825.1,tSpikein_ERCC-00165,gSpikein_ERCC-00165,42.347477,112.496605,182.813324,,None
230803,transcript,+,ERCC-00168,STRG.22826,STRG.22826.1,tSpikein_ERCC-00168,gSpikein_ERCC-00168,0.856445,2.275157,3.697258,,None
230805,transcript,+,ERCC-00170,STRG.22827,STRG.22827.1,tSpikein_ERCC-00170,gSpikein_ERCC-00170,28.368525,75.361343,122.466431,,None
230807,transcript,+,ERCC-00171,STRG.22828,STRG.22828.1,tSpikein_ERCC-00171,gSpikein_ERCC-00171,3306.709961,8784.316406,14275.009766,,None
yeet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
ddf.rename(columns = {0: "gene_id", 
1: "transcript_id",
2: "exon_number",
3: "reference_id",
4: "ref_gene_id",
5: "cov",
6: "FPKM",
7: "TPM" })

,feature,strand,seqname,gene_id,transcript_id,exon_number,reference_id,ref_gene_id,cov,FPKM,TPM,8
7,transcript,-,chr1,STRG.2,STRG.2.1,ENST00000619216.1,ENSG00000278267.1,MIR6859-1,0.772974,2.053415,3.336915,
9,transcript,-,chr1,STRG.3,STRG.3.1,ENST00000495576.1,ENSG00000239945.1,RP11-34P13.8,0.056861,0.151052,0.245468,
12,transcript,-,chr1,STRG.4,STRG.4.1,ENST00000595919.1,ENSG00000269981.1,RP11-34P13.16,0.052113,0.138439,0.224971,
14,transcript,-,chr1,STRG.5,STRG.5.1,ENST00000493797.1,ENSG00000239906.1,RP11-34P13.14,0.082559,0.219319,0.356406,
17,transcript,-,chr1,STRG.6,STRG.6.1,2.926664,7.774721,12.634358,,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...
230801,transcript,+,ERCC-00165,STRG.22825,STRG.22825.1,tSpikein_ERCC-00165,gSpikein_ERCC-00165,42.347477,112.496605,182.813324,,None
230803,transcript,+,ERCC-00168,STRG.22826,STRG.22826.1,tSpikein_ERCC-00168,gSpikein_ERCC-00168,0.856445,2.275157,3.697258,,None
230805,transcript,+,ERCC-00170,STRG.22827,STRG.22827.1,tSpikein_ERCC-00170,gSpikein_ERCC-00170,28.368525,75.361343,122.466431,,None
230807,transcript,+,ERCC-00171,STRG.22828,STRG.22828.1,tSpikein_ERCC-00171,gSpikein_ERCC-00171,3306.709961,8784.316406,14275.009766,,None
yeet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN